USE smarthire;

-- Remove corrupted test jobs
DELETE FROM jobs WHERE description LIKE '%lhfwhkrnv%' OR LENGTH(description) < 15;

-- Ensure demo recruiter exists
INSERT INTO users (id, name, email, password, role)
SELECT 100, 'Priya Recruiter', 'recruiter@smarthire.demo', '$2a$10$7R9bZl66hQn1U.rZ2/tBpe9q9LZZX5B8lJkQk7i9d2T0Cg1G4xS5C', 'RECRUITER'
WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'recruiter@smarthire.demo');

-- 25 Clean Standardized Demo Jobs
INSERT INTO jobs (title, company, location, salary, description, status, recruiter_id) VALUES
('Software Engineer', 'TechNova Solutions', 'Bangalore, Karnataka', '₹8–12 LPA', 'We are seeking a Software Engineer to design, build, and maintain core platform microservices.\n\nResponsibilities:\n- Develop robust REST APIs using Java and Spring Boot\n- Collaborate with frontend engineers to integrate user-facing features\n- Optimize database queries and improve system reliability\n- Participate in code reviews and agile sprints\n\nRequirements:\n- 2–4 years of software development experience\n- Proficiency in Java, Spring Boot, and SQL databases\n- Familiarity with Docker, Git, and CI/CD pipelines\n- Strong problem-solving and analytical mindset\n\nSkills: Java, Spring Boot, REST APIs, MySQL, Docker, Git', 'OPEN', (SELECT id FROM users WHERE email = 'recruiter@smarthire.demo' LIMIT 1)),

('Associate Software Engineer', 'NextGen Systems', 'Chennai, Tamil Nadu', '₹4–7 LPA', 'Join NextGen Systems as an Associate Software Engineer to learn, build, and support enterprise applications.\n\nResponsibilities:\n- Assist in developing backend services and web components\n- Write unit tests and maintain technical documentation\n- Troubleshoot bugs and perform minor feature enhancements\n- Work closely with senior mentors across the SDLC\n\nRequirements:\n- 0–1 years of experience or strong academic project foundation\n- Basic knowledge of Java, JavaScript, and relational databases\n- Eagerness to learn new frameworks and best practices\n- Good communication and teamwork abilities\n\nSkills: Core Java, JavaScript, SQL, HTML/CSS, Git', 'OPEN', (SELECT id FROM users WHERE email = 'recruiter@smarthire.demo' LIMIT 1)),

('Java Developer', 'CodeCraft Technologies', 'Hyderabad, Telangana', '₹6–10 LPA', 'Looking for an experienced Java Developer to develop scalable enterprise backend systems and APIs.\n\nResponsibilities:\n- Implement business logic and data persistence layers\n- Design and consume RESTful web services\n- Troubleshoot production issues and enhance throughput\n- Maintain clean, testable, and modular code\n\nRequirements:\n- 2–4 years in Core Java, Spring Framework, and JPA/Hibernate\n- Hands-on experience with MySQL or PostgreSQL\n- Knowledge of unit testing with JUnit and Mockito\n- Solid understanding of OOP principles\n\nSkills: Java, Spring, Hibernate, MySQL, JUnit, Maven', 'OPEN', (SELECT id FROM users WHERE email = 'recruiter@smarthire.demo' LIMIT 1)),

('Spring Boot Developer', 'CloudBridge Technologies', 'Pune, Maharashtra', '₹8–12 LPA', 'CloudBridge Technologies is hiring a Spring Boot Developer to build cloud-ready microservices architectures.\n\nResponsibilities:\n- Build resilient microservices with Spring Boot and Spring Cloud\n- Secure endpoints using Spring Security and JWT authentication\n- Integrate message brokers such as Kafka or RabbitMQ\n- Monitor application health and optimize JVM performance\n\nRequirements:\n- 3–5 years of backend engineering experience\n- Strong mastery of Spring Boot, Spring Data JPA, and Spring Security\n- Experience with containerization (Docker, Kubernetes)\n- Working knowledge of cloud platforms\n\nSkills: Spring Boot, Spring Security, JWT, Docker, Redis, Kafka', 'OPEN', (SELECT id FROM users WHERE email = 'recruiter@smarthire.demo' LIMIT 1)),

('Full Stack Developer', 'Vertex Digital', 'Bangalore, Karnataka', '₹10–15 LPA', 'Vertex Digital is looking for a versatile Full Stack Developer to build end-to-end web applications.\n\nResponsibilities:\n- Develop responsive web interfaces in React and modern CSS\n- Build scalable RESTful backend services using Spring Boot\n- Architect database schemas and ensure data integrity\n- Ensure smooth end-to-end user workflows and performance\n\nRequirements:\n- 3–5 years of full stack web development experience\n- Proficiency in React, JavaScript/TypeScript, Java, and MySQL\n- Experience with REST API design and state management\n- Passion for clean UI and solid backend architecture\n\nSkills: React, Java, Spring Boot, MySQL, REST APIs, TypeScript', 'OPEN', (SELECT id FROM users WHERE email = 'recruiter@smarthire.demo' LIMIT 1)),

('Frontend Developer', 'BrightStack Solutions', 'Mumbai, Maharashtra', '₹6–10 LPA', 'We are seeking a creative Frontend Developer to craft delightful, responsive user interfaces.\n\nResponsibilities:\n- Build reusable React components with clean CSS and micro-animations\n- Ensure seamless responsiveness across desktop, tablet, and mobile\n- Optimize web bundle sizes, asset delivery, and Core Web Vitals\n- Collaborate with UI/UX designers to translate Figma mockups\n\nRequirements:\n- 2–4 years of modern frontend development experience\n- Strong expertise in HTML5, CSS3, JavaScript (ES6+), and React\n- Knowledge of responsive design and cross-browser compatibility\n- Eye for detail and typography\n\nSkills: React, JavaScript, CSS3, HTML5, Vite, Responsive Design', 'OPEN', (SELECT id FROM users WHERE email = 'recruiter@smarthire.demo' LIMIT 1)),

('React Developer', 'InnovateHub', 'Coimbatore, Tamil Nadu', '₹5–8 LPA', 'InnovateHub is looking for a React Developer to accelerate product feature delivery on our flagship SaaS portal.\n\nResponsibilities:\n- Implement interactive dashboard pages and real-time state management\n- Integrate backend REST APIs and handle error boundaries\n- Write unit and component tests to ensure UI stability\n- Participate in sprint planning and design discussions\n\nRequirements:\n- 1–3 years of specialized React experience\n- Strong grasp of React Hooks, Context API, and React Router\n- Experience with modern styling approaches and CSS modules\n- Familiarity with Git version control\n\nSkills: React, React Router, Hooks, Context API, Tailwind/CSS, REST API', 'OPEN', (SELECT id FROM users WHERE email = 'recruiter@smarthire.demo' LIMIT 1)),

('Backend Developer', 'Nexora Technologies', 'Noida, Uttar Pradesh', '₹8–12 LPA', 'Nexora Technologies is seeking a dedicated Backend Developer to build high-performance data pipelines and APIs.\n\nResponsibilities:\n- Architect database tables and write efficient SQL queries\n- Implement business validations and background job workers\n- Maintain API documentation with OpenAPI / Swagger\n- Ensure high availability, fault tolerance, and security\n\nRequirements:\n- 2–4 years of backend development experience\n- Strong programming skills in Java, Node.js, or Python\n- Good understanding of relational database indexing and transactions\n- Experience with REST and API authentication protocols\n\nSkills: Java, SQL, REST APIs, Security, Spring Boot, Linux', 'OPEN', (SELECT id FROM users WHERE email = 'recruiter@smarthire.demo' LIMIT 1)),

('Node.js Developer', 'TechNova Solutions', 'Gurgaon, Haryana', '₹8–12 LPA', 'Join our core platform engineering team to build fast, asynchronous backend services in Node.js.\n\nResponsibilities:\n- Build RESTful APIs and real-time WebSocket communication channels\n- Manage asynchronous workflows, event loops, and worker queues\n- Integrate caching layers with Redis for low-latency responses\n- Maintain automated tests and CI/CD pipelines\n\nRequirements:\n- 2–4 years in Node.js, Express, and JavaScript/TypeScript\n- Experience with MongoDB and MySQL databases\n- Familiarity with async programming and performance profiling\n- Good understanding of microservices\n\nSkills: Node.js, Express, TypeScript, Redis, MongoDB, MySQL', 'OPEN', (SELECT id FROM users WHERE email = 'recruiter@smarthire.demo' LIMIT 1)),

('Python Developer', 'DataSphere Labs', 'Bangalore, Karnataka', '₹6–10 LPA', 'We are looking for a Python Developer to build data ingestion services, backend APIs, and automation scripts.\n\nResponsibilities:\n- Develop web services using FastAPI or Django\n- Build automated data extraction, transformation, and load (ETL) scripts\n- Integrate third-party APIs and machine learning models\n- Maintain test coverage and documentation\n\nRequirements:\n- 2–4 years of Python development experience\n- Proficiency with FastAPI, Flask, or Django\n- Solid SQL skills and experience with pandas/numpy\n- Good understanding of Git and Linux environments\n\nSkills: Python, FastAPI, Django, PostgreSQL, Pandas, Docker', 'OPEN', (SELECT id FROM users WHERE email = 'recruiter@smarthire.demo' LIMIT 1)),

('Data Analyst', 'Insight Analytics', 'Hyderabad, Telangana', '₹5–8 LPA', 'Insight Analytics is looking for a Data Analyst to transform complex business datasets into actionable insights.\n\nResponsibilities:\n- Analyze key business metrics, user behaviors, and revenue trends\n- Build interactive dashboards and executive reports\n- Cleanse, validate, and structure raw data for analysis\n- Present analytical findings to cross-functional stakeholders\n\nRequirements:\n- 1–3 years of data analytics experience\n- Strong proficiency in SQL and Advanced Excel\n- Experience with Power BI, Tableau, or Google Looker\n- Strong analytical reasoning and problem-solving skills\n\nSkills: SQL, Excel, Power BI, Tableau, Data Visualization, Analytics', 'OPEN', (SELECT id FROM users WHERE email = 'recruiter@smarthire.demo' LIMIT 1)),

('Junior Data Analyst', 'Insight Analytics', 'Chennai, Tamil Nadu', '₹4–7 LPA', 'We are looking for a Junior Data Analyst to support reporting, data validation, and dashboard development.\n\nResponsibilities:\n- Analyze business datasets and maintain weekly KPI trackers\n- Build automated reports and validate data accuracy\n- Prepare data summaries and dashboard charts\n- Communicate findings clearly with team leads\n\nRequirements:\n- 0–1 years of experience or strong internship background\n- Solid SQL fundamentals and Excel proficiency\n- Familiarity with Python or Power BI is a plus\n- Good communication and quantitative mindset\n\nSkills: SQL, Excel, Python, Power BI, Data Cleaning, Reporting', 'OPEN', (SELECT id FROM users WHERE email = 'recruiter@smarthire.demo' LIMIT 1)),

('Business Analyst', 'Vertex Digital', 'Pune, Maharashtra', '₹6–10 LPA', 'Vertex Digital is seeking a Business Analyst to bridge business requirements and technical product delivery.\n\nResponsibilities:\n- Gather and document business requirements, user stories, and workflows\n- Conduct stakeholder interviews and gap analysis\n- Collaborate with engineering teams to prioritize sprint backlogs\n- Perform user acceptance testing (UAT) and process verification\n\nRequirements:\n- 2–4 years as a Business Analyst in tech or IT services\n- Strong skills in requirement gathering, UML diagrams, and JIRA\n- Excellent interpersonal and presentation capabilities\n- Solid understanding of the Agile/Scrum methodology\n\nSkills: Business Analysis, Agile, JIRA, User Stories, UML, SQL', 'OPEN', (SELECT id FROM users WHERE email = 'recruiter@smarthire.demo' LIMIT 1)),

('SQL Developer', 'NextGen Systems', 'Mumbai, Maharashtra', '₹5–8 LPA', 'NextGen Systems is looking for a SQL Developer to manage, optimize, and maintain complex relational databases.\n\nResponsibilities:\n- Write and optimize complex SQL queries, stored procedures, and triggers\n- Monitor database performance, index usage, and query execution plans\n- Perform database migrations and schema refactoring\n- Ensure data security, backup integrity, and compliance\n\nRequirements:\n- 2–4 years of specialized SQL/RDBMS experience (MySQL, PostgreSQL, Oracle)\n- Deep knowledge of indexing, query tuning, and schema normalization\n- Experience with ETL pipelines and data transformation\n- Strong problem-solving skills\n\nSkills: MySQL, PostgreSQL, Stored Procedures, Query Optimization, ETL', 'OPEN', (SELECT id FROM users WHERE email = 'recruiter@smarthire.demo' LIMIT 1)),

('Power BI Developer', 'Insight Analytics', 'Delhi, India', '₹6–10 LPA', 'Looking for a Power BI Developer to design visually compelling business intelligence dashboards and data models.\n\nResponsibilities:\n- Build interactive Power BI reports and executive dashboards\n- Write DAX queries, calculated columns, and complex measures\n- Model dimensional star/snowflake schemas\n- Integrate multiple data sources including SQL and cloud data lakes\n\nRequirements:\n- 2–4 years of experience with Microsoft Power BI and DAX\n- Strong knowledge of data modeling and Power Query (M)\n- Experience connecting relational SQL databases\n- Excellent visual storytelling and presentation skills\n\nSkills: Power BI, DAX, Power Query, Data Modeling, SQL, BI Reporting', 'OPEN', (SELECT id FROM users WHERE email = 'recruiter@smarthire.demo' LIMIT 1)),

('Data Engineer', 'DataSphere Labs', 'Bangalore, Karnataka', '₹10–15 LPA', 'DataSphere Labs is hiring a Data Engineer to build high-scale data streaming and batch processing pipelines.\n\nResponsibilities:\n- Design scalable ETL/ELT pipelines using Spark, Airflow, and Python\n- Manage data lake and data warehouse architectures\n- Optimize pipeline latency, fault tolerance, and schema evolution\n- Ensure data governance and high data quality standards\n\nRequirements:\n- 3–5 years in data engineering and distributed computing\n- Hands-on expertise with Python, SQL, Apache Spark, and Kafka\n- Experience with cloud data warehouses (Snowflake, BigQuery, or Redshift)\n- Solid grasp of data modeling concepts\n\nSkills: Python, Spark, Airflow, Kafka, SQL, Data Pipelines, AWS', 'OPEN', (SELECT id FROM users WHERE email = 'recruiter@smarthire.demo' LIMIT 1)),

('QA Engineer', 'TechNova Solutions', 'Chennai, Tamil Nadu', '₹5–8 LPA', 'TechNova Solutions is seeking a QA Engineer to ensure exceptional product quality across all releases.\n\nResponsibilities:\n- Create comprehensive test plans, test cases, and test matrices\n- Execute manual functional, regression, integration, and UI testing\n- Log detailed defects in JIRA and collaborate with developers\n- Validate API responses using Postman and automated collections\n\nRequirements:\n- 2–4 years in software quality assurance\n- Strong understanding of QA methodologies and SDLC/STLC\n- Experience testing REST APIs with Postman\n- Great attention to detail and communication skills\n\nSkills: Manual Testing, Test Planning, Postman, JIRA, Regression Testing', 'OPEN', (SELECT id FROM users WHERE email = 'recruiter@smarthire.demo' LIMIT 1)),

('Automation Test Engineer', 'CodeCraft Technologies', 'Bangalore, Karnataka', '₹6–10 LPA', 'We are looking for an Automation Test Engineer to build and maintain end-to-end test automation frameworks.\n\nResponsibilities:\n- Develop automated UI tests using Selenium / Playwright / Cypress\n- Implement automated API test suites in Java or Python\n- Integrate automated tests into CI/CD build pipelines\n- Track automation test coverage and analyze execution reports\n\nRequirements:\n- 2–4 years in test automation engineering\n- Proficiency in Java or JavaScript with Selenium / Playwright\n- Experience with TestNG/JUnit and CI/CD tools like GitHub Actions/Jenkins\n- Strong debugging and root-cause analysis skills\n\nSkills: Selenium, Playwright, Java, TestNG, API Testing, CI/CD', 'OPEN', (SELECT id FROM users WHERE email = 'recruiter@smarthire.demo' LIMIT 1)),

('DevOps Engineer', 'CloudBridge Technologies', 'Hyderabad, Telangana', '₹8–12 LPA', 'CloudBridge Technologies is hiring a DevOps Engineer to automate build, deployment, and infrastructure operations.\n\nResponsibilities:\n- Design and maintain CI/CD pipelines using GitHub Actions and Jenkins\n- Manage containerized infrastructure using Docker and Kubernetes\n- Implement Infrastructure as Code (IaC) with Terraform\n- Monitor system performance, logging, and alert notifications\n\nRequirements:\n- 3–5 years of hands-on DevOps and cloud infrastructure experience\n- Strong expertise in Linux, Docker, Kubernetes, and AWS/GCP\n- Proficiency in scripting with Bash or Python\n- Solid understanding of networking and cloud security\n\nSkills: DevOps, Docker, Kubernetes, Terraform, AWS, CI/CD, Linux', 'OPEN', (SELECT id FROM users WHERE email = 'recruiter@smarthire.demo' LIMIT 1)),

('Cloud Engineer', 'Nexora Technologies', 'Pune, Maharashtra', '₹8–12 LPA', 'We are seeking a Cloud Engineer to build and manage resilient, scalable cloud architectures.\n\nResponsibilities:\n- Provision and configure cloud compute, storage, and networking resources\n- Implement automated backup, disaster recovery, and failover mechanisms\n- Optimize cloud resource utilization and monthly infrastructure costs\n- Maintain cloud security policies and IAM roles\n\nRequirements:\n- 2–4 years of cloud engineering experience on AWS, Azure, or GCP\n- Certifications such as AWS Solutions Architect or Azure Administrator\n- Knowledge of VPCs, load balancers, security groups, and cloud storage\n- Experience with Terraform or CloudFormation\n\nSkills: Cloud Engineering, AWS, Azure, Terraform, Networking, Security', 'OPEN', (SELECT id FROM users WHERE email = 'recruiter@smarthire.demo' LIMIT 1)),

('Technical Support Engineer', 'BrightStack Solutions', 'Coimbatore, Tamil Nadu', '₹4–7 LPA', 'BrightStack Solutions is looking for a Technical Support Engineer to provide tier-2 support for our enterprise software.\n\nResponsibilities:\n- Investigate and resolve complex technical inquiries and application incidents\n- Analyze application logs and database queries to identify root causes\n- Escalate unresolved bugs to core engineering teams with clear documentation\n- Maintain knowledge base articles and troubleshooting guides\n\nRequirements:\n- 1–3 years in technical application support or customer engineering\n- Basic knowledge of SQL, REST APIs, and web browser DevTools\n- Strong problem-solving ability and patient communication\n- Willingness to support customer SLAs\n\nSkills: Technical Support, SQL, Troubleshooting, REST APIs, Customer Service', 'OPEN', (SELECT id FROM users WHERE email = 'recruiter@smarthire.demo' LIMIT 1)),

('Cybersecurity Analyst', 'Vertex Digital', 'Noida, Uttar Pradesh', '₹8–12 LPA', 'Vertex Digital is hiring a Cybersecurity Analyst to protect critical infrastructure, data, and applications.\n\nResponsibilities:\n- Conduct vulnerability assessments, security audits, and penetration tests\n- Monitor security alerts and incident response channels\n- Ensure compliance with industry standards (ISO 27001, SOC 2, GDPR)\n- Champion secure coding practices and developer security training\n\nRequirements:\n- 2–4 years in cybersecurity or information security\n- Knowledge of OWASP Top 10, network protocols, and firewalls\n- Experience with security scanning tools and SIEM systems\n- Security certifications (CEH, CompTIA Security+, CISSP) preferred\n\nSkills: Cybersecurity, OWASP, Vulnerability Assessment, Network Security, SIEM', 'OPEN', (SELECT id FROM users WHERE email = 'recruiter@smarthire.demo' LIMIT 1)),

('UI/UX Designer', 'InnovateHub', 'Remote', '₹6–10 LPA', 'InnovateHub is looking for a talented UI/UX Designer to craft intuitive, modern user interfaces and experiences.\n\nResponsibilities:\n- Design user journeys, wireframes, high-fidelity mockups, and interactive prototypes in Figma\n- Maintain and expand our comprehensive design system and component library\n- Conduct user research, usability testing, and heuristic evaluations\n- Work closely with frontend developers during design handoff and QA\n\nRequirements:\n- 2–4 years of product or UI/UX design experience\n- Strong portfolio demonstrating mobile and web application design\n- Mastery of Figma, Auto Layout, Components, and Prototyping\n- Strong understanding of usability principles and typography\n\nSkills: UI/UX Design, Figma, Design Systems, Wireframing, Prototyping, Usability', 'OPEN', (SELECT id FROM users WHERE email = 'recruiter@smarthire.demo' LIMIT 1)),

('Product Analyst', 'TechNova Solutions', 'Bangalore, Karnataka', '₹6–10 LPA', 'Join TechNova Solutions as a Product Analyst to drive product experimentation, feature adoption, and roadmap decisions.\n\nResponsibilities:\n- Define product tracking events and monitor conversion funnels\n- Design and evaluate A/B experiments for new feature rollouts\n- Translate customer behavioral data into actionable product requirements\n- Collaborate with product managers and engineers on sprint goals\n\nRequirements:\n- 2–4 years in product analytics or digital product operations\n- Proficiency in SQL and analytics tools (Mixpanel, Amplitude, Google Analytics)\n- Strong statistical understanding and experiment design skills\n- Excellent written and verbal communication\n\nSkills: Product Analytics, SQL, A/B Testing, Mixpanel, User Funnels, KPIs', 'OPEN', (SELECT id FROM users WHERE email = 'recruiter@smarthire.demo' LIMIT 1)),

('Graduate Engineer Trainee', 'NextGen Systems', 'Chennai, Tamil Nadu', '₹4–7 LPA', 'NextGen Systems invites recent graduates to join our flagship Graduate Engineer Trainee (GET) program.\n\nResponsibilities:\n- Participate in structured technology training in Java, Web, and Cloud\n- Contribute to real-world software modules under mentorship\n- Learn agile software development practices, git workflows, and code hygiene\n- Complete milestone projects and collaborate with senior engineers\n\nRequirements:\n- B.E. / B.Tech / MCA in Computer Science, IT, or related technical disciplines\n- Foundational knowledge of Data Structures, Algorithms, and OOP concepts\n- Strong enthusiasm to learn and grow in a fast-paced environment\n- Good problem-solving mindset and communication skills\n\nSkills: Java, Data Structures, OOP, SQL, Problem Solving, Learning Agility', 'OPEN', (SELECT id FROM users WHERE email = 'recruiter@smarthire.demo' LIMIT 1));
